# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Life, My Town
description: > # this means to ignore newlines until "baseurl:"
  ‘My Life, My Town’ documents a slice of time in the lives of teenagers from small Missouri towns. 
  These are the youth who make up the hope and future of rural life – if they decide to stay. 
  Our hope is that getting to know the children these villages raise will provide a unique look at the day-to-day joys and struggles of rural life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mylifemytown.kbia.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems: ['jekyll-less']

defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: /:year/:slug/